MapGroupPointers::
; pointers to the first map header of each map group
	dw MapGroup1
	dw MapGroup2
	dw MapGroup3

MapGroup1:
	map_header Rpp, TILESET_RPP, INDOOR, VIRIDIAN_FOREST, MUSIC_VIRIDIAN_FOREST, 0, PALETTE_NITE, FISHGROUP_POND

MapGroup2:
	map_header PokeCenter2F, TILESET_POKECENTER, INDOOR, SPECIAL_MAP, MUSIC_POKEMON_CENTER, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header TradeCenter, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header Colosseum, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header HiddenTreeGrotto, TILESET_FOREST, CAVE, SPECIAL_MAP, MUSIC_NONE, 1, PALETTE_NITE, FISHGROUP_SHORE

MapGroup3:
	map_header NewBarkTown, TILESET_JOHTO_TRADITIONAL, TOWN, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header KrissHouse1F, TILESET_JOHTO_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KrissHouse2F, TILESET_JOHTO_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
