MapGroupPointers::
; pointers to the first map header of each map group
	dw MapGroup1
	dw MapGroup2

MapGroup1:
	map_header ViridianForest, TILESET_RPP, INDOOR, VIRIDIAN_FOREST, MUSIC_VIRIDIAN_FOREST, 0, PALETTE_NITE, FISHGROUP_POND

MapGroup2:
	map_header KrissHouse2F, TILESET_JOHTO_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header NewBarkTown, TILESET_JOHTO_TRADITIONAL, TOWN, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_AUTO, FISHGROUP_OCEAN
